CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(50) NOT NULL UNIQUE,
                       display_name VARCHAR(100) NOT NULL,
                       created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE workspaces (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL UNIQUE,
                            created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE channels (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL,
                          workspace_id BIGINT NOT NULL REFERENCES workspaces (id),
                          created_at TIMESTAMPTZ NOT NULL,
                          CONSTRAINT uq_channels_workspace_name UNIQUE (workspace_id, name)
);

CREATE TABLE messages (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          content VARCHAR(2000) NOT NULL,
                          channel_id BIGINT NOT NULL REFERENCES channels (id),
                          sender_id BIGINT NOT NULL REFERENCES users (id),
                          created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_messages_channel_created_at ON messages (channel_id, created_at);